baseurl = "http://hnrck.io"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]
languageCode = "en-us"
publishDir = "."
theme = "hnrck-identity-theme"
themesDir = "themes"
title = "Henrick Deschamps"
[params]
appleicon = "apple.png"
custom_css = ["background.css", "icons.css"]
favicon_ico = "favicon.ico"
favicon_ico_sizes = "16x16 32x32"
[params.contact]
email = "contact@hnrck.io"
[params.footer]
copyright = "Henrick Deschamps"
[params.license]
link = "https://creativecommons.org/licenses/by-sa/4.0/legalcode"
name = "CC-BY-SA-4.0"
[params.personal]
avatar = "korea.jpg"
biography = ""
livesIn = "[Toulouse, France](https://www.google.fr/maps/place/Toulouse/@43.6006786,1.3628012,12z/data=!3m1!4b1!4m5!3m4!1s0x12aebb6fec7552ff:0x406f69c2f411030!8m2!3d43.604652!4d1.444209)"
name = "Henrick Deschamps"
position = "Ph.D.-Eng. in Critical Distributed Systems"
scope = ["Designer, developper and maintainer for [seaplanes](https://github.com/hnrck/seaplanes) and [rrosace](https://github.com/hnrck/rrosace)", "Check out my [blog](https://hnrck.io/blog)"]
[[params.credits]]
link = "https://html5up.net"
text = "Design by"
title = "HTML5UP"
[[params.social]]
icon = "fa-twitter"
link = "https://twitter.com/dhnrck"
target = "_blank"
title = "Twitter"
[[params.social]]
icon = "fa-github"
link = "https://github.com/hnrck"
target = "_blank"
title = "Github"
[[params.social]]
icon = "fa-linkedin"
link = "https://www.linkedin.com/in/henrick-deschamps"
target = "_blank"
title = "LinkedIn"
[[params.social]]
icon = "fa-blog"
link = "https://hnrck.io/blog"
target = "_blank"
title = "Blog"
[[params.social]]
icon = "fa-file"
link = "https://hnrck.keybase.pub/cv_henrick_deschamps.pdf"
target = "_blank"
title = "CV"
[[params.social]]
icon = "fa-envelope"
link = "mailto:contact@hnrck.io"
target = "_blank"
title = "Message"
[[params.social]]
icon = "fa-keybase"
link = "https://keybase.io/hnrck"
target = "_blank"
title = "Keybase"
