baseurl = "http://hnrck.io"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]
languageCode = "en-us"
theme = "hnrck-identity-theme"
themesDir = "themes"
title = "Henrick Deschamps"
publishDir = "."

[params]

  # Images settings
  # Icons, backgrounds and avatars folders are placed in theme's static/images folder.
  # You may place your images in corresponding folders and then set only filenames below to
  # change page's appearance

  # Site icons
  favicon_ico = "favicon.ico"
  favicon_ico_sizes = "16x16 32x32"
  appleicon = "apple.png"

  # Additional options to supplement icons served
  #favicon_png = "favicon.png"
  #favicon_png_sizes = "96x96"
  #favicon_svg = "favicon.svg"

  # Link custom assets relative to /static
  #custom_js  = [""]
  custom_css = ["background.css", "icons.css"]

  # Customization switches
  # Overwrite FontAwesome: see icons.css
  #custom_icons = true
  # Overwrite background: see background.css
  #custom_background = true

  # Personal data
  [params.personal]
    # If name is not set, author is used
    name = "Henrick Deschamps"
    # Avatars can be written to images/avatars/
    avatar = "korea.jpg"
    position = "Ph.D.-Eng. in Critical Distributed Systems"
    livesIn = "[Toulouse, France](https://www.google.fr/maps/place/Toulouse/@43.6006786,1.3628012,12z/data=!3m1!4b1!4m5!3m4!1s0x12aebb6fec7552ff:0x406f69c2f411030!8m2!3d43.604652!4d1.444209)"
    scope = [
        "Designer, developper and maintainer for [seaplanes](https://github.com/hnrck/seaplanes) and [rrosace](https://github.com/hnrck/rrosace)",
        "Check out my [blog](https://hnrck.io/blog)",
      ]
    biography = """"""

  # Contact form settings

  [params.contact]
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    email = "contact@hnrck.io"

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.

    #postURL = "https://example.com/mailout/"

    # enable = true
    # title = "Ping Me!"
    # namePlaceholder = "Name"
    # emailPlaceholder = "Email"
    # messagePlaceholder = "Message"
    # buttonText = "Send it"
    # success = "Thank you for contacting me."
    # error = "Message could not be send. Please contact us at contact@hnrck.io"

    # Google invisible captcha
    #[params.contact.captcha]
    #  sitekey = ""


    # Add optional form fields to identify contact forms.
    #[[params.contact.fields.hidden]]
    # name = "someID"
    # value = "example.com"

    #[[params.contact.fields.hidden]]
    # Special values for name such as "page" and "site" will be autofilled
    # name = "page"

  # Social settings
  # You may change these with your social links or add others

  [[params.social]]
    title = "Twitter"
    icon = "fa-twitter"
    link = "https://twitter.com/dhnrck"
    target = "_blank"

  [[params.social]]
    title = "Github"
    icon = "fa-github"
    link = "https://github.com/hnrck"
    target = "_blank"

  [[params.social]]
    title = "LinkedIn"
    icon = "fa-linkedin"
    link = "https://www.linkedin.com/in/henrick-deschamps"
    target = "_blank"

  [[params.social]]
    title = "Blog"
    icon = "fa-blog"
    link = "https://hnrck.io/blog"
    target = "_blank"

  [[params.social]]
    title = "CV"
    icon = "fa-file"
    link = "https://hnrck.keybase.pub/cv_henrick_deschamps.pdf"
    target = "_blank"

  [[params.social]]
    title = "Message"
    icon = "fa-envelope"
    link = "mailto:contact@hnrck.io"
    target = "_blank"

  [[params.social]]
    title = "Keybase"
    icon = "fa-keybase"
    link = "https://keybase.io/hnrck"
    target = "_blank"


  # Footer settings
  [params.footer]
    # If copyright is not set, author is used
    copyright = "Henrick Deschamps"

  # Page license
  [params.license]
    link = "https://creativecommons.org/licenses/by-sa/4.0/legalcode"
    name = "CC-BY-SA-4.0"

  # Credits
  [[params.credits]]
    # Title is used as URL text
    title = "HTML5UP"
    # Text will be used to explain the credit
    text = "Design by"
    link = "https://html5up.net"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="
