baseurl = "http://example.org"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]
languageCode = "en-us"
theme = "hugo-identity-theme"
themesDir = "themes"
title = "Hugo Identity Theme"
[params]
appleicon = "apple.png"
favicon_ico = "favicon.ico"
favicon_ico_sizes = "16x16 32x32"
[params.contact]
buttonText = "Send it"
email = "your@email.com"
emailPlaceholder = "Email"
enable = false
error = "Message could not be send. Please contact us at "
messagePlaceholder = "Message"
namePlaceholder = "Name"
success = "Thank you for contacting us."
title = "Touch Me!"
[params.footer]
[params.license]
link = "https://creativecommons.org/licenses/by-sa/4.0/legalcode"
name = "CC-BY-SA-4.0"
[params.personal]
avatar = "pro.jpg"
biography = "    French communicating distributed systems Ph.D. and engineer, \n    I am interested in real-time distributed systems.\n  I am looking for serious technological challenges, I would like to contribute to the conception and implementation of complex systems in a team, and to participate in the demonstration of these systems\n"
livesIn = "[Toulouse, France](https://www.google.fr/maps/place/Toulouse/@43.6006786,1.3628012,12z/data=!3m1!4b1!4m5!3m4!1s0x12aebb6fec7552ff:0x406f69c2f411030!8m2!3d43.604652!4d1.444209)"
name = "Henrick Deschamps"
position = "Ph.D. Engineer"
scope = ["Maintainer for [rrosace](https://github.com/hnrck/rrosace), [seaplanes](https://github.com/hnrck/rrosace), and [rrosace on seaplanes](https://github.com/hnrck/rrosace_seaplanes)"]
[[params.credits]]
link = "https://html5up.net"
text = "Design by"
title = "HTML5UP"
[[params.social]]
icon = "fa-twitter"
link = "https://twitter.com/dhnrck"
target = "_blank"
title = "Twitter"
[[params.social]]
icon = "fa-github"
link = "https://github.com/hnrck"
target = "_blank"
title = "Github"
[[params.social]]
icon = "fa-linkedin"
link = "https://www.linkedin.com/in/henrick-deschamps"
target = "_blank"
title = "LinkedIn"
